# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMqxCRwnXXxT91wX5d4wtz-kFFhsaXWR
"""

pip install tensorflow

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files
from PIL import Image

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalize pixel values
x_train, x_test = x_train / 255.0, x_test / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10)  # 10 output classes
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=10,
                    validation_data=(x_test, y_test))

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print("\nTest accuracy:", test_acc)

from tensorflow.keras.utils import load_img, img_to_array

# After training the model:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

# --- Loop for repeated predictions ---
while True:
    print("\n📤 Upload an image for classification (CIFAR-10)...")
    uploaded = files.upload()

    for filename in uploaded.keys():
        try:
            # Load and preprocess image
            img = Image.open(filename).convert("RGB")
            img_resized = img.resize((32, 32))
            img_array = img_to_array(img_resized) / 255.0
            img_array = np.expand_dims(img_array, axis=0)

            # Predict
            prediction = probability_model.predict(img_array)
            predicted_class = class_names[np.argmax(prediction)]

            # Show result
            print(f"\n✅ Predicted Class: {predicted_class}")
            plt.imshow(img)
            plt.title(f"Prediction: {predicted_class}")
            plt.axis("off")
            plt.show()

        except Exception as e:
            print(f"⚠️ Error processing {filename}: {e}")

    again = input("\n🔁 Classify another image? (yes/no): ").strip().lower()
    if again not in ['yes', 'y']:
        print("\n👋 Done! Thanks for using the CIFAR-10 classifier.")
        break

